version: '3.7'

services:
    te-tjanster:
        container_name: te-tjanster
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - traefik-public
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - nginx-logs:/var/log/nginx
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.te-tjanster.rule=Host(`jobs.notasoftwaredevelopmentcompany.com`)'
            - 'traefik.http.routers.te-tjanster.tls=true'
            - 'traefik.http.routers.te-tjanster.tls.certresolver=myresolver'
            - 'traefik.http.routers.te-tjanster.tls.options=nasdc-website@file'
            - 'traefik.http.routers.te-tjanster.middlewares=security-headers-te-tjanster@file'
        restart: always

volumes:
    nginx-logs:

networks:
    traefik-public:
        external: true
